#!/usr/bin/env php
<?php

require(__DIR__ . '/../vendor/autoload.php');

use Sil\PhpEnv\Env;
use Sil\SilAuth\config\ConfigManager;
use Sil\SilAuth\models\User;

ConfigManager::initializeYii2WebApp(['components' => ['db' => [
    'dsn' => sprintf(
        'mysql:host=%s;dbname=%s',
        Env::get('MYSQL_HOST'),
        Env::get('MYSQL_DATABASE')
    ),
    'username' => Env::get('MYSQL_USER'),
    'password' => Env::get('MYSQL_PASSWORD'),
]]]);

$usersToAdd = [
  [
    'first_name' => 'Bob',
    'last_name' => 'Adams',
    'username' => 'BOB_ADAMS',
    'email' => 'bob_adams@acme.org',
    'employee_id' => '99999',
  ],
];
foreach ($usersToAdd as $userToAdd) {
  $user = new User($userToAdd);
  if ( ! $user->save()) {
    echo var_export($user->getErrors(), true);
    exit(1);
  }
}
exit(0);
