#!/usr/bin/env php
<?php

require(__DIR__ . '/../vendor/autoload.php');

use Sil\PhpEnv\Env;
use Sil\SilAuth\config\ConfigManager;
use Sil\SilAuth\models\User;

ConfigManager::initializeYii2WebApp(['components' => ['db' => [
    'dsn' => sprintf(
        'mysql:host=%s;dbname=%s',
        Env::get('MYSQL_HOST'),
        Env::get('MYSQL_DATABASE')
    ),
    'username' => Env::get('MYSQL_USER'),
    'password' => Env::get('MYSQL_PASSWORD'),
]]]);

$usersToAdd = [
  [
    'first_name' => 'Bob',
    'last_name' => 'Adams',
    'username' => 'BOB_ADAMS',
    'email' => 'bob_adams@acme.org',
    'employee_id' => '10101',
  ],
  [
    'first_name' => 'Rob',
    'last_name' => 'Holt',
    'username' => 'ROB_HOLT',
    'email' => 'rob_holt@acme.org',
    'employee_id' => '10121',
  ],
];
try {
  foreach ($usersToAdd as $userToAdd) {
    $user = new User($userToAdd);
    if ( ! $user->save()) {
      echo var_export($user->getErrors(), true);
    }
  }
} catch (\Throwable $e) {
  echo $e->getMessage() . PHP_EOL;
  exit(1);
}
exit(0);
