#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

define('YII_DEBUG', false);
define('YII_ENV', 'production');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/../vendor/autoload.php');

use Sil\PhpEnv\Env;
use Sil\SilAuth\config\ConfigManager;

$application = ConfigManager::getYii2ConsoleApp(['components' => ['db' => [
    'dsn' => sprintf(
        'mysql:host=%s;dbname=%s',
        Env::get('MYSQL_HOST'),
        Env::get('MYSQL_DATABASE')
    ),
    'username' => Env::get('MYSQL_USER'),
    'password' => Env::get('MYSQL_PASSWORD'),
]]]);
$exitCode = $application->run();
exit($exitCode);
